name: Deploy to Firebase on Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Write Firebase key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ./firebase-key.json

      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Clean up service account key
        run: rm ./firebase-key.json
        if: ${{ always() }}
